spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: AUTHENTICATION
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: USER-MANAGEMENT
          uri: http://localhost:8082
          predicates:
            - Path=/userManagement/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true



server:
  port: 8443


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    org.springframework: TRACE